name: Build the ap

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: easycontrolfork

      - name: Build and Locate
        run: |
          mkdir -p app/src/main/res/raw
          ./gradlew :server:copyRelease
          ./gradlew :app:assembleRelease
          echo "Listing all files in app/build/outputs:"
          find app/build/outputs -name "*.apk"
        working-directory: easycontrolfork

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jsjsj-auuw
          path: |
            **/*.apk

